version: 2
updates:
  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'weekly'
    labels:
      - dependencies
    commit-message:
      prefix: 'build'
      include: 'scope'
    open-pull-requests-limit: 5

  - package-ecosystem: 'npm'
    directory: '/'
    open-pull-requests-limit: 25
    schedule:
      interval: 'weekly'
    labels:
      - dependencies
    commit-message:
      prefix: 'build'
      include: 'scope'
    groups:
      prisma-packages:
        patterns:
          - 'prisma'
          - '@prisma/client'
          - '@prisma/adapter-pg'
      nextjs-react:
        patterns:
          - 'next'
          - 'next-auth'
          - '@next-auth/*'
          - 'react'
          - 'react-dom'
          - 'eslint-config-next'
      typescript-eslint:
        patterns:
          - 'typescript'
          - 'eslint'
          - 'eslint-*'
          - 'typescript-eslint'
          - '@typescript-eslint/*'
      serwist:
        patterns:
          - 'serwist'
          - '@serwist/*'
      testing:
        patterns:
          - 'vitest'
          - '@vitest/*'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    labels:
      - dependencies
    commit-message:
      prefix: 'ci'
      include: 'scope'
