version: "3.5"

services:
    main:
        # used for CI script to know which images to start on deployment
        image: rwgrim/docker-noop
        depends_on:
            - hekbar_cocktails

    hekbar_cocktails:
        image: registry.hek.whka.de/hekbar/hekbar-cocktails:${REGISTRY_TAG}
        depends_on:
            - backup_system
        networks:
            - webgateway
            - hekbar_cocktails_net
        environment:
            - DATABASE_URL=postgresql://hekbaruser:${HEKBAR_COCKTAILS_DB_PASSWORD}@hekbar_cocktails_db:5432/hekbar_cocktails
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.hekbar_cocktails.entrypoints=websecure"
            - "traefik.http.routers.hekbar_cocktails.rule=Host(`bar-cocktails.hek.whka.de`)"
            - "traefik.http.routers.hekbar_cocktails.middlewares=ipcheck-hekinternal@file"
            - "traefik.http.routers.hekbar_cocktails.service=hekbar_cocktails"
            - "traefik.http.services.hekbar_cocktails.loadbalancer.server.port=3000"
            - "traefik.docker.network=webgateway"
            - "traefik.tags=migrated"

    hekbar_cocktails_db:
#        ports:
#            -   "42345:5432"
        networks:
            - hekbar_cocktails_net
        environment:
            - POSTGRES_PASSWORD=${HEKBAR_COCKTAILS_DB_PASSWORD}
        volumes:
            - hekbar_cocktails_db_data:/var/lib/postgresql/data/

    backup_system:
        restart: always
        image: registry.hek.whka.de/hekit/hekservices/hekvolbackup:prod
        container_name: hekbar_cocktails_backup_system
        volumes:
            - /backup-data/:/backup
            - /backup/:/mnt/backup1
            - hekbar_cocktails_db_data:/mounts/hekbar_cocktails_db_data
    restore_system:
        image: registry.hek.whka.de/hekit/hekservices/hekvolrestore:prod
        container_name: hekbar_cocktails_restore_system
        volumes:
            - /backup-data/:/backup
            - hekbar_cocktails_db_data:/mounts/hekbar_cocktails_db_data

volumes:
    hekbar_cocktails_db_data:
        name: hekbar_cocktails_db_data

networks:
    webgateway:
        external: true
