/**
 * Prisma → public DTO mapping for units and unit conversions. Keeps the /api/v1
 * contract clean: no `workspaceId` (already implied by the path) and no relation
 * counts.
 */
import type { Unit, UnitConversion } from '@generated/prisma/client';
import type { UnitConversionDto, UnitDto } from '@lib/schemas/units';

export function toUnitDto(unit: Pick<Unit, 'id' | 'name'>): UnitDto {
  return {
    id: unit.id,
    name: unit.name,
  };
}

export function toUnitConversionDto(conversion: Pick<UnitConversion, 'id' | 'fromUnitId' | 'toUnitId' | 'factor' | 'autoGenerated'>): UnitConversionDto {
  return {
    id: conversion.id,
    fromUnitId: conversion.fromUnitId,
    toUnitId: conversion.toUnitId,
    factor: conversion.factor,
    autoGenerated: conversion.autoGenerated,
  };
}
