-- AlterTable
ALTER TABLE "CocktailRecipeIngredient"
    ADD COLUMN "unitId" TEXT;

-- CreateTable
CREATE TABLE "Unit"
(
    "id"          TEXT NOT NULL,
    "name"        TEXT NOT NULL,
    "workspaceId" TEXT NOT NULL,

    CONSTRAINT "Unit_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "UnitConversion"
(
    "id"            TEXT             NOT NULL,
    "fromUnitId"    TEXT             NOT NULL,
    "toUnitId"      TEXT             NOT NULL,
    "factor"        DOUBLE PRECISION NOT NULL,
    "autoGenerated" BOOLEAN          NOT NULL DEFAULT false,
    "workspaceId"   TEXT             NOT NULL,

    CONSTRAINT "UnitConversion_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "IngredientVolume"
(
    "id"           TEXT             NOT NULL,
    "volume"       DOUBLE PRECISION NOT NULL,
    "ingredientId" TEXT             NOT NULL,
    "unitId"       TEXT             NOT NULL,
    "workspaceId"  TEXT             NOT NULL,

    CONSTRAINT "IngredientVolume_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Unit_name_workspaceId_key" ON "Unit" ("name", "workspaceId");

-- CreateIndex
CREATE UNIQUE INDEX "UnitConversion_toUnitId_fromUnitId_workspaceId_key" ON "UnitConversion" ("toUnitId", "fromUnitId", "workspaceId");

-- CreateIndex
CREATE UNIQUE INDEX "IngredientVolume_ingredientId_workspaceId_unitId_key" ON "IngredientVolume" ("ingredientId", "workspaceId", "unitId");

-- AddForeignKey
ALTER TABLE "CocktailRecipeIngredient"
    ADD CONSTRAINT "CocktailRecipeIngredient_unitId_fkey" FOREIGN KEY ("unitId") REFERENCES "Unit" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Unit"
    ADD CONSTRAINT "Unit_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "UnitConversion"
    ADD CONSTRAINT "UnitConversion_fromUnitId_fkey" FOREIGN KEY ("fromUnitId") REFERENCES "Unit" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "UnitConversion"
    ADD CONSTRAINT "UnitConversion_toUnitId_fkey" FOREIGN KEY ("toUnitId") REFERENCES "Unit" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "UnitConversion"
    ADD CONSTRAINT "UnitConversion_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "IngredientVolume"
    ADD CONSTRAINT "IngredientVolume_ingredientId_fkey" FOREIGN KEY ("ingredientId") REFERENCES "Ingredient" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "IngredientVolume"
    ADD CONSTRAINT "IngredientVolume_unitId_fkey" FOREIGN KEY ("unitId") REFERENCES "Unit" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "IngredientVolume"
    ADD CONSTRAINT "IngredientVolume_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
