/**
 * Version-agnostic business logic for units and unit conversions (v1). Same DB
 * operations as the legacy handlers, but returns clean public DTOs
 * (lib/api/dto/units.ts). Legacy routes remain wrapped-but-untouched and keep
 * their raw Prisma shapes.
 */
import { Graph, shortestPath } from 'graph-data-structure';
import prisma from '../../../prisma/prisma';
import { updateTranslation } from '../../../pages/api/workspaces/[workspaceId]/admin/translation';
import { toUnitConversionDto, toUnitDto } from '@lib/api/dto/units';
import type { Prisma, Unit, UnitConversion, Workspace } from '@generated/prisma/client';
import type { UnitConversionCreateInput, UnitConversionDto, UnitConversionUpdateInput, UnitCreateInput, UnitDto } from '@lib/schemas/units';

export async function listUnits(workspace: Workspace, opts: { search?: string }): Promise<UnitDto[]> {
  const where: Prisma.UnitWhereInput = { workspaceId: workspace.id };
  if (opts.search) {
    where.name = { contains: opts.search, mode: 'insensitive' };
  }
  const units = await prisma.unit.findMany({ where });
  return units.map(toUnitDto);
}

export async function createUnit(workspace: Workspace, input: UnitCreateInput): Promise<UnitDto> {
  await updateTranslation(workspace.id, input.name, input.translations ?? {});

  const created = await prisma.unit.create({
    data: {
      name: input.name,
      workspace: { connect: { id: workspace.id } },
    },
  });

  return toUnitDto(created);
}

export async function deleteUnit(unitId: string): Promise<UnitDto> {
  const deleted = await prisma.unit.delete({ where: { id: unitId } });
  return toUnitDto(deleted);
}

export async function listUnitConversions(workspace: Workspace): Promise<UnitConversionDto[]> {
  const conversions = await prisma.unitConversion.findMany({ where: { workspaceId: workspace.id } });
  return conversions.map(toUnitConversionDto);
}

export async function createUnitConversion(workspace: Workspace, input: UnitConversionCreateInput): Promise<UnitConversionDto[]> {
  await prisma.unitConversion.create({
    data: {
      fromUnit: { connect: { id: input.fromUnitId } },
      toUnit: { connect: { id: input.toUnitId } },
      factor: input.factor,
      workspace: { connect: { id: workspace.id } },
    },
  });
  await prisma.unitConversion.create({
    data: {
      fromUnit: { connect: { id: input.toUnitId } },
      toUnit: { connect: { id: input.fromUnitId } },
      factor: 1 / input.factor,
      autoGenerated: true,
      workspace: { connect: { id: workspace.id } },
    },
  });

  const conversions = await regenerateUnitConversions(workspace.id);
  return conversions.map(toUnitConversionDto);
}

export async function updateUnitConversion(workspace: Workspace, unitConversionId: string, input: UnitConversionUpdateInput): Promise<UnitConversionDto> {
  const updated = await prisma.unitConversion.update({
    where: { id: unitConversionId },
    data: { factor: input.factor },
  });
  await regenerateUnitConversions(workspace.id);
  return toUnitConversionDto(updated);
}

export async function deleteUnitConversion(workspace: Workspace, unitConversionId: string): Promise<UnitConversionDto> {
  const deleted = await prisma.unitConversion.delete({ where: { id: unitConversionId } });
  await regenerateUnitConversions(workspace.id);
  return toUnitConversionDto(deleted);
}

/**
 * Faithful replica of the legacy regenerateUnitConversions (pages/api/workspaces/
 * [workspaceId]/units/conversions/index.ts): recomputes all auto-generated
 * conversions from the manually defined ones via shortest-path traversal.
 */
export async function regenerateUnitConversions(workspaceId: string): Promise<UnitConversion[]> {
  // Recalculate all unit conversions
  await prisma.unitConversion.deleteMany({
    where: {
      workspaceId: workspaceId,
      AND: {
        autoGenerated: true,
      },
    },
  });

  const nodes: Unit[] = await prisma.unit.findMany({ where: { workspaceId: workspaceId } });
  const paths: UnitConversion[] = await prisma.unitConversion.findMany({ where: { workspaceId: workspaceId } });

  const graph = new Graph<string>();
  nodes.forEach((node) => graph.addNode(node.id));
  paths.forEach((path) => {
    graph.addEdge(path.fromUnitId, path.toUnitId);
    graph.addEdge(path.toUnitId, path.fromUnitId);
  });

  function generatePairCombinations(units: string[]): [string, string][] {
    const combinations: [string, string][] = [];

    for (let i = 0; i < units.length; i++) {
      for (let j = i + 1; j < units.length; j++) {
        combinations.push([units[i], units[j]]);
        combinations.push([units[j], units[i]]);
      }
    }

    return combinations;
  }

  const combinations = generatePairCombinations(nodes.map((node) => node.id));

  const allConnections: string[][] = [];

  combinations.forEach((combination) => {
    try {
      const path = shortestPath(graph, combination[0], combination[1]);
      allConnections.push(path.nodes);
    } catch {}
  });

  const allConversions: UnitConversion[] = paths;

  for (const connection of allConnections) {
    const fromOrig = connection[0];
    let to = connection[1];
    let factor = 1;
    for (let i = 0; i < connection.length - 1; i++) {
      const from = connection[i];
      to = connection[i + 1];
      const foundFactor =
        paths.find((path) => path.fromUnitId === from && path.toUnitId === to)?.factor ||
        1 / (paths.find((path) => path.fromUnitId === to && path.toUnitId === from)?.factor ?? 1) ||
        1 ||
        1;
      factor *= foundFactor;
    }
    if (!paths.find((path) => path.fromUnitId === fromOrig && path.toUnitId === to)) {
      allConversions.push(
        await prisma.unitConversion.create({
          data: {
            fromUnit: { connect: { id: fromOrig } },
            toUnit: { connect: { id: to } },
            factor: factor,
            autoGenerated: true,
            workspace: { connect: { id: workspaceId } },
          },
        }),
      );
    }
    if (!paths.find((path) => path.fromUnitId === to && path.toUnitId === fromOrig)) {
      allConversions.push(
        await prisma.unitConversion.create({
          data: {
            fromUnit: { connect: { id: to } },
            toUnit: { connect: { id: fromOrig } },
            factor: 1 / factor,
            autoGenerated: true,
            workspace: { connect: { id: workspaceId } },
          },
        }),
      );
    }
  }

  return allConversions;
}
