-- AlterTable
ALTER TABLE "CocktailCard"
    ADD COLUMN "archived"  BOOLEAN      NOT NULL DEFAULT false,
    ADD COLUMN "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
