-- CreateEnum
CREATE TYPE "Permission" AS ENUM ('COCKTAILS_READ', 'COCKTAILS_CREATE', 'COCKTAILS_UPDATE', 'COCKTAILS_DELETE', 'INGREDIENTS_READ', 'INGREDIENTS_CREATE', 'INGREDIENTS_UPDATE', 'INGREDIENTS_DELETE', 'GARNISHES_READ', 'GARNISHES_CREATE', 'GARNISHES_UPDATE', 'GARNISHES_DELETE', 'GLASSES_READ', 'GLASSES_CREATE', 'GLASSES_UPDATE', 'GLASSES_DELETE', 'UNITS_READ', 'UNITS_CREATE', 'UNITS_UPDATE', 'UNITS_DELETE', 'QUEUE_READ', 'QUEUE_CREATE', 'QUEUE_UPDATE', 'QUEUE_DELETE', 'STATISTICS_READ', 'STATISTICS_CREATE', 'STATISTICS_UPDATE', 'STATISTICS_DELETE', 'CARDS_READ', 'CARDS_CREATE', 'CARDS_UPDATE', 'CARDS_DELETE', 'CALCULATIONS_READ', 'CALCULATIONS_CREATE', 'CALCULATIONS_UPDATE', 'CALCULATIONS_DELETE', 'WORKSPACE_READ', 'WORKSPACE_UPDATE', 'USERS_READ', 'USERS_CREATE', 'USERS_UPDATE', 'USERS_DELETE', 'ACTIONS_READ', 'ACTIONS_CREATE', 'ACTIONS_UPDATE', 'ACTIONS_DELETE', 'ICE_READ', 'ICE_CREATE', 'ICE_UPDATE', 'ICE_DELETE', 'JOIN_CODES_READ', 'JOIN_CODES_CREATE', 'JOIN_CODES_UPDATE', 'JOIN_CODES_DELETE', 'JOIN_REQUESTS_READ', 'JOIN_REQUESTS_CREATE', 'JOIN_REQUESTS_UPDATE', 'JOIN_REQUESTS_DELETE', 'RATINGS_READ', 'RATINGS_CREATE', 'RATINGS_UPDATE', 'RATINGS_DELETE');

-- CreateTable
CREATE TABLE "WorkspaceApiKey" (
    "id" TEXT NOT NULL,
    "workspaceId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "keyHash" TEXT NOT NULL,
    "expiresAt" TIMESTAMP(3),
    "lastUsedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "createdByUserId" TEXT NOT NULL,

    CONSTRAINT "WorkspaceApiKey_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ApiKeyPermission" (
    "id" TEXT NOT NULL,
    "apiKeyId" TEXT NOT NULL,
    "permission" "Permission" NOT NULL,
    "endpointPattern" TEXT,

    CONSTRAINT "ApiKeyPermission_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "WorkspaceApiKey_workspaceId_idx" ON "WorkspaceApiKey"("workspaceId");

-- CreateIndex
CREATE INDEX "WorkspaceApiKey_keyHash_idx" ON "WorkspaceApiKey"("keyHash");

-- CreateIndex
CREATE INDEX "ApiKeyPermission_apiKeyId_idx" ON "ApiKeyPermission"("apiKeyId");

-- CreateIndex
CREATE UNIQUE INDEX "ApiKeyPermission_apiKeyId_permission_endpointPattern_key" ON "ApiKeyPermission"("apiKeyId", "permission", "endpointPattern");

-- AddForeignKey
ALTER TABLE "WorkspaceApiKey" ADD CONSTRAINT "WorkspaceApiKey_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "WorkspaceApiKey" ADD CONSTRAINT "WorkspaceApiKey_createdByUserId_fkey" FOREIGN KEY ("createdByUserId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ApiKeyPermission" ADD CONSTRAINT "ApiKeyPermission_apiKeyId_fkey" FOREIGN KEY ("apiKeyId") REFERENCES "WorkspaceApiKey"("id") ON DELETE CASCADE ON UPDATE CASCADE;
