/**
 * Zod schemas + ResourceApiDocs for the Units resource (v1), including unit
 * conversions. Pure module (zod + type-only enums) so scripts/generate-openapi.ts
 * can import it without pulling the Prisma runtime. Responses describe the clean
 * public DTOs (see lib/api/dto/units.ts), NOT the raw Prisma shape.
 */
import { z } from '@lib/openapi/zod';
import { WorkspaceIdParam } from '@lib/schemas/common';
import type { ResourceApiDoc } from '@lib/openapi/types';

/** Public unit DTO — no Prisma-isms and no `workspaceId` (implied by the path). */
export const UnitDtoSchema = z
  .object({
    id: z.string(),
    name: z.string(),
  })
  .openapi('Unit');

export type UnitDto = z.infer<typeof UnitDtoSchema>;

/** Public unit-conversion DTO — no `workspaceId` (implied by the path). */
export const UnitConversionDtoSchema = z
  .object({
    id: z.string(),
    fromUnitId: z.string(),
    toUnitId: z.string(),
    factor: z.number().openapi({ description: 'Multiplier to convert a quantity from the source unit to the target unit.' }),
    autoGenerated: z.boolean().openapi({ description: 'Whether this conversion was derived automatically from other conversions.' }),
  })
  .openapi('UnitConversion');

export type UnitConversionDto = z.infer<typeof UnitConversionDtoSchema>;

/** Optional per-language display-name overrides, keyed by language code. */
const TranslationsSchema = z
  .record(z.string(), z.string())
  .openapi({ description: 'Optional display-name translations keyed by language code, e.g. { "en": "Centiliter" }.' });

export const UnitCreateSchema = z
  .object({
    name: z.string().min(1),
    translations: TranslationsSchema.optional(),
  })
  .openapi('UnitCreateInput');

export const UnitListQuerySchema = z.object({
  search: z.string().optional().openapi({ description: 'Case-insensitive name filter.' }),
});

export const UnitItemParams = WorkspaceIdParam.extend({ unitId: z.string() });

export type UnitCreateInput = z.infer<typeof UnitCreateSchema>;
export type UnitListQuery = z.infer<typeof UnitListQuerySchema>;

export const UnitConversionCreateSchema = z
  .object({
    fromUnitId: z.string().min(1),
    toUnitId: z.string().min(1),
    factor: z.coerce.number().openapi({ description: 'Multiplier to convert a quantity from the source unit to the target unit.' }),
  })
  .openapi('UnitConversionCreateInput');

export const UnitConversionUpdateSchema = z
  .object({
    factor: z.coerce.number().openapi({ description: 'Multiplier to convert a quantity from the source unit to the target unit.' }),
  })
  .openapi('UnitConversionUpdateInput');

export const UnitConversionItemParams = WorkspaceIdParam.extend({ unitConversionId: z.string() });

export type UnitConversionCreateInput = z.infer<typeof UnitConversionCreateSchema>;
export type UnitConversionUpdateInput = z.infer<typeof UnitConversionUpdateSchema>;

export const unitsCollectionApiDoc = {
  basePath: '/workspaces/{workspaceId}/units',
  legacyPath: true,
  operations: {
    GET: {
      roles: ['USER'],
      permission: 'UNITS_READ',
      tags: ['Units'],
      summary: 'List units',
      description: 'List all units of a workspace, optionally filtered by name.',
      params: WorkspaceIdParam,
      query: UnitListQuerySchema,
      response: z.array(UnitDtoSchema),
    },
    POST: {
      roles: ['ADMIN'],
      permission: null,
      tags: ['Units'],
      summary: 'Create unit',
      params: WorkspaceIdParam,
      body: UnitCreateSchema,
      response: UnitDtoSchema,
    },
  },
} satisfies ResourceApiDoc;

export const unitsItemApiDoc = {
  basePath: '/workspaces/{workspaceId}/units/{unitId}',
  legacyPath: true,
  operations: {
    DELETE: {
      roles: ['ADMIN'],
      permission: null,
      tags: ['Units'],
      summary: 'Delete unit',
      params: UnitItemParams,
      response: UnitDtoSchema,
    },
  },
} satisfies ResourceApiDoc;

export const unitConversionsCollectionApiDoc = {
  basePath: '/workspaces/{workspaceId}/units/conversions',
  legacyPath: true,
  operations: {
    GET: {
      roles: ['USER'],
      permission: null,
      tags: ['Units'],
      summary: 'List unit conversions',
      description: 'List all unit conversions of a workspace.',
      params: WorkspaceIdParam,
      response: z.array(UnitConversionDtoSchema),
    },
    POST: {
      roles: ['ADMIN'],
      permission: null,
      tags: ['Units'],
      summary: 'Create unit conversion',
      description: 'Create a unit conversion (plus its inverse) and regenerate all derived conversions.',
      params: WorkspaceIdParam,
      body: UnitConversionCreateSchema,
      response: z.array(UnitConversionDtoSchema),
    },
  },
} satisfies ResourceApiDoc;

export const unitConversionsItemApiDoc = {
  basePath: '/workspaces/{workspaceId}/units/conversions/{unitConversionId}',
  legacyPath: true,
  operations: {
    PUT: {
      roles: ['ADMIN'],
      permission: 'UNITS_UPDATE',
      tags: ['Units'],
      summary: 'Update unit conversion',
      description: 'Update a conversion factor and regenerate all derived conversions.',
      params: UnitConversionItemParams,
      body: UnitConversionUpdateSchema,
      response: UnitConversionDtoSchema,
    },
    DELETE: {
      roles: ['ADMIN'],
      permission: null,
      tags: ['Units'],
      summary: 'Delete unit conversion',
      description: 'Delete a conversion and regenerate all derived conversions.',
      params: UnitConversionItemParams,
      response: UnitConversionDtoSchema,
    },
  },
} satisfies ResourceApiDoc;
