name: Release

on:
  push:
    branches:
      - main
      - master

jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
      packages: write
      id-token: write

    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.JG_SEMANTIC_RELEASE_BOT_APP_ID }}
          private_key: ${{ secrets.JG_SEMANTIC_RELEASE_BOT_PRIVATE_KEY }}

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ steps.generate_token.outputs.token }}
      
      - uses: actions/setup-node@v2
        with:
          node-version: 20
      - run: yarn install
      - run: yarn build
      - run: yarn semantic-release
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
          DOCKER_REGISTRY_USER: ${{ github.actor }}
          DOCKER_REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
